### PR TITLE
Apply BCs/Changed timestepper 

### PR DESCRIPTION
**Pull request by ShyamSS-95**
- Added case for obtaining k-omega values to compare against dispersion relations.
- Added apply_boundary_conditions functions for fields and distribution function.
- Changed timestepper.py structure to make the splitting schemes more clear. Now the accuracy for the timesplit schemes also has a test.
- Changed method by which the testing flags are passed to the functions.

### CODE REVIEW

**Comment by mchandra** [comment]
What are the unit tests for `apply_boundary_conditions` ?

**Comment by mchandra** [comment]
Not sure whats going in `lib/nonlinear_solver/apply_boundary_conditions.py#L37`

This is what I have in mind:
```
# Need to set only characteristics flowing into the domain (p1 > 0 for the left side of the domain). 

# Outflowing characteristics (p1 < 0 should not be touched; need not be set)

f_left_boundary = self._convert_to_p_expanded(f_left_boundary) # (Nq1 * Nq2, Np1, Np2, Np3)
self.f = self._convert_to_p_expanded(self.f) # (Nq1 * Nq2, Np1, Np2, Np3)

f_left_boundary_right_going_chars = f_left[:, Np1/2:]
f_right_going_chars = self.f[:, Np1/2:]

# Need to reshape to (Nq1, Nq2, ...) in order to only set the values in the ghost zones
f_left_boundary_right_going_chars = self._convert_to_q_expanded(f_left_boundary_right_going_chars)
f_right_going_chars = self._convert_to_q_expanded(f_right_going_chars)
f_right_going_chars[:N_ghost, :] = f_left_boundary_right_going_chars

# self.f now has the right going chars (p1>0) of the ghost zones at the left boundary set
```

**Comment by ShyamSS-95** [comment]
For the test of the mirror boundary condition in `example_problems/gaussian_mirror_pulse`, we obtain the following convergence plot after evolving for a single time-period(return to mean position after a single bounce off the walls):

**Comment by ShyamSS-95** [comment]
We get this result when the convergence test is performed until N = 1024:
convergence

**Pull request merged**
