### PR TITLE
Multiple Species

### PR DESCRIPTION
**Pull request by ShyamSS-95**
- Multiple species have been implemented in both linear and nonlinear solver.
- Documentation has been added for each function with most folders containing a `README` to explain it's contents.
- Upwind flux has been implemented for p-space as well.
- Addition of tests for checking the convergence of the methods applied in p-space.
- The option of adding ghost zones in p-space implemented.
- Shearing box boundary condition implemented along with unit tests.

NOTE: Unit tests for each of the solvers haven't been updated with the changes made to add species.

### CODE REVIEW

**Comment by mchandra** [comment]
* Create a `utils` folder above `linear` and `nonlinear` and move things like `_calculate_q_center` etc there. These functions are used all over the place and in so many post-processing scripts that it'd be useful to be able to import them
* Make `fields_solver` take the same options as `nonlinear_solver` / `linear_solver`. 
* Inconsistency: `nonlinear/fields/fields.py` vs `linear/fields/fields_solver.py`
* Example usage of `user-defined` fields.
* Rewrite `nonlinear/tests/test_fdtd_explicit.py` using `fields_solver` and with functions from `utils`
* Remove option for `N_g_p` ? 

[REVIEW IN PROGRESS]

**Comment by mchandra** [comment]
Has the option for `N_g_p` been removed? There seems to be code related to it in `finite_volume/df_dt_fvm.py`, `compute_moments.py` etc

**Comment by ShyamSS-95** [comment]
@mchandra Yeah. As far as I remember, I'd removed it from most core functions. I just saw that I've forgotten it in the `load` functions, and one place in `apply_dirichlet_bcs`. Which version are you looking at?

**Comment by ShyamSS-95** [comment]
Had to be deleted due to a large number of image files which were also committed. Fresh PR for the same will be opened

**Pull request closed without merging**
