### PR TITLE
Refactored Code

### PR DESCRIPTION
**Pull request by ShyamSS-95**
Please go through the format being used. There are a few issues with the current version of the code(commit `de92a47`):

- Linear solver seems to have a bug in the fields component. The current version of the code has the amplitude of density increasing after some time.
- Testing wasn't carried out for the nonlinear solver. There was an issue with BLAS(required for PETSc) on my computer due to which I couldn't prototype and test. I'll test the same on a server tomorrow.

### CODE REVIEW

**Comment by gitansh95** [comment]
I have done the following steps :

- Installed `libopenblas`, and `AMDAPPSDK-3.0` and fixed broken link.

- Did not install CUDA

- Built and installed ArrayFire from source. The default installation directory is `/usr/local`. Ran `make test` in the build folder. Test Number 116 (Test_approx1_opencl) gets stuck for (>2) hours. I had to abort the process using `Ctrl+C`. All previous tests passed.

- Installed arrayfire-python, added `export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH` to my `.bashrc` file .

- Cloned Boltzmann_solver, and ran `make init`. This installed all the dependencies for Boltzmann_solver.

- Ran `make test`. It gave the following result `Collected 0 items`, `No test ran in 0.00 seconds`

- In the directory `Boltzmann_solver/example_problems/nonrelativistic_boltzmann/testing_folder`, i ran `python main.py`. The python file execution got stuck with no output on the terminal. The process did not end with a `Ctrl + C`, I closed the terminal to kill the process. Using `print` statements, I found that the problem is being caused by the line `import arrayfire as af`. So I reinstalled arrayfire-python, tried changing the `LD_LIBRARY_PATH`. But I still get the same problem.

My python version is 2.7.
Please suggest how I should proceed?

**Comment by mchandra** [comment]
1. *Never* install anything in root (`/usr/`). Install everything locally in your home folder. Scientific software like `arrayfire` is constantly evolving and is best installed locally.
2. What backends in `arrayfire` did you compile?
3. This code needs python 3. Needs to be stated in the documentation. I suggest you install it locally using Anaconda python : https://www.continuum.io/downloads#linux

**Comment by gitansh95** [comment]
Oh I see that by default only the CPU backend gets compiled in ArrayFire. So I have only the CPU backend compiled, and don't have the OpenCL backend enabled. Is that why the `arrayfire` Test Number 116 (`Test_approx1_opencl`) gets stuck? I expected it to print '`Failed`' and move on to the next tests.

I will reinstall ArrayFire in my home folder.

**Comment by ShyamSS-95** [comment]
I suggest you use the following command to configure:`cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_OPENCL=ON -DCMAKE_INSTALL_PREFIX=package`.
The above command needs to be run from the build directory that you create in the arrayfire folder

**Comment by gitansh95** [comment]
I started from scratch keeping in mind the above comments.
1. `In /usr/local/lib/python2.7/`, removed `petsc*`, `arrayfire*`
2. Removed `AMD-APP-SDKInstaller-v3.0.130.136` and `Intel_SDK_for_OpenCL`
3. Cloned the `Boltzmann_solver` git repo to `/home/gitansh95/work/git/Boltzmann_solver` with `git clone https://github.com/ShyamSS-95/Boltzmann_solver.git`
4. `git checkout -b refactor-library` and `git pull origin refactor-library`
5. General Dependencies : `sudo apt-get install -y build-essential git cmake libfreeimage-dev`
                          `sudo apt-get install -y cmake-curses-gui`
6. CPU Backend Dependencies : `sudo apt-get install libopenblas-dev libfftw3-dev liblapacke-dev`
7. Skipping CUDA Dependencies
8. OpenCL Backend Dependencies : `AMD-APP-SDKInstaller-v3.0` (not `Intel_SDK_for_OpenCL`, but I have Intel core 3rd gen GPU).
Double clicked on AMD-APP-SDKInstaller.tar.bz2 file, and extracted to `/home/gitansh95`. In terminal, `./AMD-APP-SDK...linux.sh`. Install directory is `/home/gitansh95`.
The following 3 lines were done automatically by the installer.
Exported `AMDAPPSDKROOT=/home/gitansh95/AMDAPPSDK-3.0` via `/home/gitansh95/.bashrc`.
Exported `AMDAPPSDKROOT=/home/gitansh95/AMDAPPSDK-3.0` via `/home/gitansh95/.bashrc`.
Exported `OPENCL_VENDOR_PATH=/home/gitansh95/AMDAPPSDK-3.0/etc/OpenCL/vendors/` via `/home/gitansh95/.bashrc`.
On 64 bit installs, AMD installs with broken link. I did -  `ln -sf sdk/libOpenCL.so.1 libOpenCL.so`  to fix that.

`sudo apt-get install opencl-headers`
`sudo apt-get install libboost-all-dev`

9. ArrayFire graphics library Dependencies
`sudo apt-get install libglfw3-dev libfontconfig1-dev`

10. Cloned arrayfire in `/home/gitansh95/work/git/arrayfire` with `git clone https://github.com/arrayfire/arrayfire.git`
    `git submodule init`
    `git submodule update`

11. Building arrayfire:
    `mkdir build` (indside arrayfire folder)
    `cd build`
    `cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_OPENCL=ON -DCMAKE_INSTALL_PREFIX=package`

screenshot from 2017-08-07 19-20-03
    `make -j2`
I get this error, and the build fails.
error

I did complete the build a few times before this error started showing up.

**Comment by ShyamSS-95** [comment]
Did you check your OpenCL installation? Use `sudo apt install clinfo`, and the execute `clinfo` from the terminal. For a more thorough check refer to https://wiki.tiker.net/OpenCLHowTo#Testing.

Although this is unrelated to the build failure, did you get python3 installed? That'll be necessary to run the python wrapper.

**Comment by gitansh95** [comment]
- From the link you have above, I found that I did not install an opencl driver, so downloaded AMD driver http://support.amd.com/en-us/download/desktop?os=Linux+x86#, extracted it in `/home/gitansh95/`, and then `bash ./amd-driver-installer-15.302-x86.x86_64.run --extract `.

- Did this
`TGT_DIR="/opt/amd-opencl-icd-15.302/lib"`
` mkdir -p "$TGT_DIR"`
` cp ./arch/x86_64/usr/lib64/* "$TGT_DIR"`
` sudo -i`
` echo "$TGT_DIR/libamdocl64.so" > /etc/OpenCL/vendors/amd.icd`
`exit`
- I already have `AMD-APP-SDK` as mentioned in my above comment.
- I added this to my `.bashrc` : `export LD_LIBRARY_PATH=/home/gitansh95/AMDAPPSDK-3.0/lib/x86_64:$LD_LIBRARY_PATH`
-The following lines were added by the AMD-APP-SDKInstaller to my `.bashrc`
`export AMDAPPSDKROOT="/home/gitansh95/AMDAPPSDK-3.0"`
`export OPENCL_VENDOR_PATH="/home/gitansh95/AMDAPPSDK-3.0/etc/OpenCL/vendors/"`
- Installed `clinfo` with `sudo apt-get install clinfo`.
- When I run `clinfo`, it gives me this  ```terminate called after throwing an instance of 'cl::Error'
what():  clGetPlatformIDs
Aborted (core dumped)```

**Comment by ShyamSS-95** [comment]
Can you try again with the Intel OpenCL runtimes? Don't use the SDK:Download [this](http://registrationcenter-download.intel.com/akdlm/irc_nas/9019/opencl_runtime_16.1.1_x64_ubuntu_6.4.0.25.tgz)

**Comment by gitansh95** [comment]
This helped. I deleted all AMD-APP-SDK stuff I had installed earlier and now I'm going with the intel binaries that you have suggested above. The build completes. I ran `make test` yesterday, but the tests got stuck at around Test 130. I'm running `make` test again now
I have installed anaconda3 in `/home/gitansh95/anaconda3`.
This is the output for `which python` : `/home/gitansh95/anaconda3/bin/python`
Now using pip I have installed arrayfire python bindings  - `pip install arrayfire`.
In `.bashrc` I have `export LD_LIBRARY_PATH=${HOME}/arrayfire/lib:$LD_LIBRARY_PATH`
But when I try to do `python -m arrayfire.tests` I get :
```Traceback (most recent call last):
  File "/home/gitansh95/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/gitansh95/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/arrayfire/__init__.py", line 56, in <module>
    from .library    import *
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/arrayfire/library.py", line 600, in <module>
    backend = _clibrary()
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/arrayfire/library.py", line 576, in __init__
    raise RuntimeError("Could not load any ArrayFire libraries.\n" + more_info_str)
RuntimeError: Could not load any ArrayFire libraries.
Please look at https://github.com/arrayfire/arrayfire-python/wiki for more information.
```
I did export the arrayfire library path. Do you know what is going on?

**Comment by mchandra** [comment]
Try the following:

```
Step 1:
-------
login3.stampede(4)$ ls -al /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so*
lrwxrwxrwx 1 tg829690 G-803035      19 Jun  3 01:14 /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so -> libstdc++.so.6.0.19
lrwxrwxrwx 1 tg829690 G-803035      19 Jun  3 01:14 /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so.6 -> libstdc++.so.6.0.19
-rwxr-xr-x 2 tg829690 G-803035 1055192 Sep 18  2015 /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so.6.0.19

Step 2:
-------
login3.stampede(5)$ rm /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so
login3.stampede(6)$ rm /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so.6

Step 3:
-------
login3.stampede(9)$ ln -s /opt/apps/gcc/4.9.1/lib64/libstdc++.so.6.0.20 /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so
login3.stampede(7)$ ln -s /opt/apps/gcc/4.9.1/lib64/libstdc++.so.6.0.20 /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so.6

Step 4:
-------
login3.stampede(10)$ ls -al /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so*
lrwxrwxrwx 1 tg829690 G-803035      45 Jun  5 05:51 /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so -> /opt/apps/gcc/4.9.1/lib64/libstdc++.so.6.0.20
lrwxrwxrwx 1 tg829690 G-803035      45 Jun  5 05:50 /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so.6 -> /opt/apps/gcc/4.9.1/lib64/libstdc++.so.6.0.20
-rwxr-xr-x 2 tg829690 G-803035 1055192 Sep 18  2015 /work/03669/tg829690/Quazar/anaconda3/lib/libstdc++.so.6.0.19

```

**Comment by mchandra** [comment]
What is "test 130" ? Show the terminal output. Also show the output of htop.

**Comment by ShyamSS-95** [comment]
I've already given him the anaconda fix for arrayfire. That's not the issue here

**Comment by mchandra** [comment]
This is my `petsc` configure command:

```
./configure --prefix=/home/mani/Downloads/petsc_3.7.5_installation/ --with-debugging=0 COPTFLAGS="-O3 -march=native" CXXOPTFLAG S="-O3 -march=native" --with-hdf5=1 --download-hdf5 --with-clean=1 --with-memalign=64 --known-level1-dcache-size=32768 --known-level1-dcache-linesize=64 --known-level1-dcache-assoc=8 --download-mpich=1
```
Everything will get installed to `/home/mani/Downloads/petsc_3.7.5_installation`. To run the code you need to do : 
```
$ /home/mani/Downloads/petsc_3.7.5_installation/bin/mpirun -np NP ipython code.py
```
where `NP` is the number of mpi ranks. If you are running only on your computer, just use `NP=1`. The OpenCL backend will automatically use all your cores. If you are running on two nodes, each with say 16 cores, then use `NP=2'

**Comment by gitansh95** [comment]
I did `make test` again. It is stuck on Test 126(Test_canny_opencl).
Here is the output for `htop`
htop

Meanwhile I'm installing petsc and petsc4py.

**Comment by gitansh95** [comment]
Temporarily running on binaries for ArrayFire.

When I run `main.py` in `examples_problems/nonrelativistic_boltzmann/testing_folder/`, the following error shows up : 
```
 Traceback (most recent call last):
  File "main.py", line 84, in <module>
    pl.savefig('plot.png')
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/pyplot.py", line 697, in savefig
    res = fig.savefig(*args, **kwargs)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1573, in savefig
    self.canvas.print_figure(*args, **kwargs)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_qt5agg.py", line 222, in print_figure
    FigureCanvasAgg.print_figure(self, *args, **kwargs)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py", line 2252, in print_figure
    **kwargs)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 545, in print_png
    FigureCanvasAgg.draw(self)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 464, in draw
    self.figure.draw(self.renderer)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py", line 1144, in draw
    renderer, self, dsu, self.suppressComposite)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py", line 2426, in draw
    mimage._draw_list_compositing_images(renderer, self, dsu)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/image.py", line 139, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py", line 63, in draw_wrapper
    draw(artist, renderer, *args, **kwargs)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1138, in draw
    renderer)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/axis.py", line 1078, in _get_tick_bboxes
    extent = tick.label1.get_window_extent(renderer)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 967, in get_window_extent
    bbox, info, descent = self._get_layout(self._renderer)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/text.py", line 353, in _get_layout
    ismath=False)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py", line 230, in get_text_width_height_descent
    renderer=self)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 676, in get_text_width_height_descent
    dvifile = self.make_dvi(tex, fontsize)
  File "/home/gitansh95/anaconda3/lib/python3.6/site-packages/matplotlib/texmanager.py", line 423, in make_dvi
    report))
RuntimeError: LaTeX was not able to process the following string:
b'lp'
Here is the full report generated by LaTeX: 
```

I needed  `sudo apt-get install texlive texlive-latex-extra dvipng` to get rid of this error.
We need to add these to the dependency.

**Comment by gitansh95** [comment]
When I run `make test`, I get this error : 
```
gitansh95@computer:~/work/git/Boltzmann_solver$ make test
py.test tests
============================= test session starts ==============================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/gitansh95/work/git/Boltzmann_solver, inifile:
collected 0 items 

========================= no tests ran in 0.10 seconds =========================
Makefile:5: recipe for target 'test' failed
make: *** [test] Error 5
```

When I run `py.test`, I get `Collected 22 items` and then my computer hangs, and I have to restart to get it back to normal again.

**Comment by gitansh95** [comment]
I am running individual unit tests from `lib/linear_solver/tests`.
Here is my report for the same :

1. `test_compute_moments.py`

```
============================================================= test session starts =============================================================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/gitansh95/work/git/Boltzmann_solver/lib/linear_solver/tests, inifile:
collected 1 items 

test_compute_moments.py F

================================================================== FAILURES ===================================================================
____________________________________________________________ test_compute_moments _____________________________________________________________

    def test_compute_moments():
      obj       = test()
      rho_calc  = compute_moments(obj, 'density')
    
      # This formatting is difficult to read
      error_rho = af.sum(af.abs(rho_calc - (1 + 0.01 * af.sin(2*np.pi*obj.q1[:, :, 0] + \
                                                              4*np.pi*obj.q2[:, :, 0]
                                                             )
                        )))/rho_calc.elements()
    
      E_calc = compute_moments(obj, 'energy')
    
      error_E = af.sum(af.abs(E_calc - 3*(1 + 0.01 * af.sin(2*np.pi*obj.q1[:, :, 0] + \
                                                            4*np.pi*obj.q2[:, :, 0]
                                                           )
                                         )**2 \
    
                                     - 3*(1 + 0.01 * af.sin(2*np.pi*obj.q1[:, :, 0] + \
                                                            4*np.pi*obj.q2[:, :, 0]
                                                           )
                                         )**3
    
                             )
                       )/rho_calc.elements()
    
      mom_p1_calc = compute_moments(obj, 'mom_p1_bulk')
      mom_p2_calc = compute_moments(obj, 'mom_p2_bulk')
      mom_p3_calc = compute_moments(obj, 'mom_p3_bulk')
    
      error_p1 = af.sum(af.abs(mom_p1_calc - (1 + 0.01 * af.sin(2*np.pi*obj.q1[:, :, 0] + \
                                                                4*np.pi*obj.q2[:, :, 0]
                                                               )
                       ))**2)/rho_calc.elements()
    
      error_p2 = af.sum(af.abs(mom_p2_calc - (1 + 0.01 * af.sin(2*np.pi*obj.q1[:, :, 0] + \
                                                                4*np.pi*obj.q2[:, :, 0]
                                                               )
                       ))**2)/rho_calc.elements()
    
      error_p3 = af.sum(af.abs(mom_p3_calc - (1 + 0.01 * af.sin(2*np.pi*obj.q1[:, :, 0] + \
                                                                4*np.pi*obj.q2[:, :, 0]
                                                               )
                       ))**2)/rho_calc.elements()
    
      # Should the error be <1e-14, or is 1e-13 okay?
>     assert(error_rho<1e-13)
E     assert 4.190951580356169e-08 < 1e-13

test_compute_moments.py:138: AssertionError
------------------------------------------------------------ Captured stderr call -------------------------------------------------------------
4 warnings generated.
========================================================== 1 failed in 23.37 seconds ==========================================================
```

2. `test_EM_fields_solver.py`

```
============================================================= test session starts =============================================================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/gitansh95/work/git/Boltzmann_solver/lib/linear_solver/tests, inifile:
collected 1 items 

test_EM_fields_solver.py F

================================================================== FAILURES ===================================================================
______________________________________________________ test_compute_electrostatic_fields ______________________________________________________

    def test_compute_electrostatic_fields():
    
      test_obj = test()
>     compute_electrostatic_fields(test_obj)

test_EM_fields_solver.py:51: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_EM_fields_solver.test object at 0x7fba41e2c2e8>

    def compute_electrostatic_fields(self):
      """
      Computes the electrostatic fields by making use of the Poisson equation:
      div^2 phi = rho
      """
      rho_hat = 2 * af.fft2(self.compute_moments('density'))/(self.N_q1 * self.N_q2) # Scaling Appropriately
      rho_hat = af.tile(rho_hat, 1, 1, self.N_p1 * self.N_p2 * self.N_p3)
>     phi_hat = self.physical_system.params.charge_electron * rho_hat/(self.k_q1**2 + self.k_q2**2)
E     AttributeError: 'test' object has no attribute 'physical_system'

../EM_fields_solver.py:13: AttributeError
------------------------------------------------------------ Captured stderr call -------------------------------------------------------------
4 warnings generated.
4 warnings generated.
========================================================== 1 failed in 31.59 seconds ==========================================================
```

3. `test_dfdp_background.py`

```
def test_df_dp_background():

# Need comments here describing what is happening in each block of code.
# Testing what, against what, and in what form should the output be.

  N       = 32 * np.arange(1, 10)

  error_1 = np.zeros(N.size)
  error_2 = np.zeros(N.size)
  error_3 = np.zeros(N.size)

  for i in range(N.size):
    obj = test(N[i])

    calculate_dfdp_background(obj)

    dfdp1_expected = -2 * obj.p1 * af.exp(-obj.p1**2)*af.exp(-obj.p2**2)*af.exp(-obj.p3**2)
    dfdp2_expected = -2 * obj.p2 * af.exp(-obj.p1**2)*af.exp(-obj.p2**2)*af.exp(-obj.p3**2)
    dfdp3_expected = -2 * obj.p3 * af.exp(-obj.p1**2)*af.exp(-obj.p2**2)*af.exp(-obj.p3**2)

    dfdp1_expected = af.tile(af.reorder(af.flat(dfdp1_expected), 2, 3, 0, 1), obj.N_q1, obj.N_q2, 1)
    dfdp2_expected = af.tile(af.reorder(af.flat(dfdp2_expected), 2, 3, 0, 1), obj.N_q1, obj.N_q2, 1)
    dfdp3_expected = af.tile(af.reorder(af.flat(dfdp3_expected), 2, 3, 0, 1), obj.N_q1, obj.N_q2, 1)

    error_1[i] = af.sum(af.abs(dfdp1_expected - obj.dfdp1_background))/dfdp1_expected.elements()
    error_2[i] = af.sum(af.abs(dfdp2_expected - obj.dfdp2_background))/dfdp2_expected.elements()
    error_3[i] = af.sum(af.abs(dfdp3_expected - obj.dfdp3_background))/dfdp3_expected.elements()
  
  poly_1 = np.polyfit(np.log10(N), np.log10(error_1), 1)
  poly_2 = np.polyfit(np.log10(N), np.log10(error_2), 1)
  poly_3 = np.polyfit(np.log10(N), np.log10(error_3), 1)

  assert(abs(poly_1[0] + 4)<0.2 and abs(poly_2[0] + 4)<0.2 and abs(poly_3[0] + 4)<0.2)
```

Could not check whether it passes or fails because running this test causes my laptop to hang.

4. I have added comments to `test_dump.py`, describing what each block of code does.
5. In some places the error is being checked to be less than 1e-13 and 5e-14. Is that okay or is more precision needed?

I'm now reviewing unit tests for `lib/nonlinear_solver/tests`

**Comment by gitansh95** [comment]
Here is the report for `lib/nonlinear-solver/tests` :

1. Need comments in all unit tests, describing what is being tested, against what, and the threshold for pass/fail.

2. `test_compute_electrostatic_fields.py`
```
============================================================= test session starts =============================================================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/gitansh95/work/git/Boltzmann_solver/lib/nonlinear_solver/tests, inifile:
collected 1 items 

test_compute_electrostatic_fields.py F

================================================================== FAILURES ===================================================================
______________________________________________________ test_compute_electrostatic_fields ______________________________________________________

    def test_compute_electrostatic_fields():
    
      error_E1 = np.zeros(5)
      error_E2 = np.zeros(5)
    
      N = 2**np.arange(5, 10)
    
      for i in range(N.size):
        obj = test(N[i])
>       compute_electrostatic_fields(obj)

test_compute_electrostatic_fields.py:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_compute_electrostatic_fields.test object at 0x7f1e8cb656d8>

    def compute_electrostatic_fields(self):
      # Obtaining the left-bottom corner coordinates
      # (lowest values of the canonical coordinates in the local zone)
      # Additionally, we also obtain the size of the local zone
      ((i_q1_lowest, i_q2_lowest), (N_q1_local, N_q2_local)) = self._da_ksp.getCorners()
    
      pde = Poisson2D(self)
      phi = self._da_ksp.createGlobalVec()
      rho = self._da_ksp.createGlobalVec()
    
      phi_local = self._da_ksp.createLocalVec()
    
      A = PETSc.Mat().createPython([phi.getSizes(), rho.getSizes()], comm = self._da_ksp.comm)
      A.setPythonContext(pde)
      A.setUp()
    
      ksp = PETSc.KSP().create()
    
      ksp.setOperators(A)
      ksp.setType('cg')
    
      pc = ksp.getPC()
      pc.setType('none')
    
      N_g = self.N_ghost
      ksp.setTolerances(atol = 1e-5)
>     pde.formRHS(rho, self.physical_system.params.charge_electron *\
                       np.array(self.compute_moments('density')[N_g:-N_g, N_g:-N_g] - 1)
                 )
E     AttributeError: 'test' object has no attribute 'physical_system'

../EM_fields_solver/electrostatic.py:76: AttributeError
========================================================== 1 failed in 1.72 seconds ===========================================================
```

3. `test_fdtd_explicit.py`
```
============================================================= test session starts =============================================================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/gitansh95/work/git/Boltzmann_solver/lib/nonlinear_solver/tests, inifile:
collected 2 items 

test_fdtd_explicit.py FF

================================================================== FAILURES ===================================================================
_______________________________________________________________ test_fdtd_mode1 _______________________________________________________________

    def test_fdtd_mode1():
    
      error_B1 = np.zeros(5)
      error_B2 = np.zeros(5)
      error_E3 = np.zeros(5)
    
      N = 2**np.arange(5, 10)
    
      for i in range(N.size):
    
        obj = test(N[i])
    
        N_g = obj.N_ghost
    
        obj.B1[N_g:-N_g, N_g:-N_g] =\
        gauss1D(obj.q2[N_g:-N_g, N_g:-N_g], 0.1)
    
        obj.B2[N_g:-N_g, N_g:-N_g] =\
        gauss1D(obj.q1[N_g:-N_g, N_g:-N_g], 0.1)
    
        dt   = obj.dq1/2
        time = np.arange(dt, 1 + dt, dt)
    
        E3_initial = obj.E3.copy()
        B1_initial = obj.B1.copy()
        B2_initial = obj.B2.copy()
    
        obj.J1, obj.J2, obj.J3 = 0, 0, 0
    
        for time_index, t0 in enumerate(time):
>         fdtd(obj, dt)

test_fdtd_explicit.py:86: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_fdtd_explicit.test object at 0x7f8284c1def0>, dt = 0.015625

    def fdtd(self, dt):
    
      # E's and B's are staggered in time such that
      # B's are defined at (n + 1/2), and E's are defined at n
    
      # Positions of grid point where field quantities are defined:
      # B1 --> (i, j + 1/2)
      # B2 --> (i + 1/2, j)
      # B3 --> (i + 1/2, j + 1/2)
    
      # E1 --> (i + 1/2, j)
      # E2 --> (i, j + 1/2)
      # E3 --> (i, j)
    
      # J1 --> (i + 1/2, j)
      # J2 --> (i, j + 1/2)
      # J3 --> (i, j)
    
      # The communicate function transfers the data from the local vectors to the global
      # vectors, in addition to dealing with the boundary conditions:
      self._communicate_fields()
    
      dq1 = self.dq1
      dq2 = self.dq2
    
>     B1 = self.B1_fdtd
E     AttributeError: 'test' object has no attribute 'B1_fdtd'

../EM_fields_solver/fdtd_explicit.py:31: AttributeError
_______________________________________________________________ test_fdtd_mode2 _______________________________________________________________

    def test_fdtd_mode2():
    
      error_E1 = np.zeros(3)
      error_E2 = np.zeros(3)
      error_B3 = np.zeros(3)
    
      N = 2**np.arange(5, 8)
    
      for i in range(N.size):
    
        obj = test(N[i])
        N_g = obj.N_ghost
    
        obj.E1[N_g:-N_g, N_g:-N_g] =\
        gauss1D(obj.q2[N_g:-N_g, N_g:-N_g], 0.1)
    
        obj.E2[N_g:-N_g, N_g:-N_g] =\
        gauss1D(obj.q1[N_g:-N_g, N_g:-N_g], 0.1)
    
        dt   = obj.dq1/2
        time = np.arange(dt, 1 + dt, dt)
    
        B3_initial = obj.B3.copy()
        E1_initial = obj.E1.copy()
        E2_initial = obj.E2.copy()
    
        obj.J1, obj.J2, obj.J3 = 0, 0, 0
    
        for time_index, t0 in enumerate(time):
>         fdtd(obj, dt)

test_fdtd_explicit.py:139: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_fdtd_explicit.test object at 0x7f8284c2d5f8>, dt = 0.015625

    def fdtd(self, dt):
    
      # E's and B's are staggered in time such that
      # B's are defined at (n + 1/2), and E's are defined at n
    
      # Positions of grid point where field quantities are defined:
      # B1 --> (i, j + 1/2)
      # B2 --> (i + 1/2, j)
      # B3 --> (i + 1/2, j + 1/2)
    
      # E1 --> (i + 1/2, j)
      # E2 --> (i, j + 1/2)
      # E3 --> (i, j)
    
      # J1 --> (i + 1/2, j)
      # J2 --> (i, j + 1/2)
      # J3 --> (i, j)
    
      # The communicate function transfers the data from the local vectors to the global
      # vectors, in addition to dealing with the boundary conditions:
      self._communicate_fields()
    
      dq1 = self.dq1
      dq2 = self.dq2
    
>     B1 = self.B1_fdtd
E     AttributeError: 'test' object has no attribute 'B1_fdtd'

../EM_fields_solver/fdtd_explicit.py:31: AttributeError
========================================================== 2 failed in 1.75 seconds ===========================================================
```
4. `test_fft_poisson.py`
```
============================================================= test session starts =============================================================
platform linux -- Python 3.6.1, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/gitansh95/work/git/Boltzmann_solver/lib/nonlinear_solver/tests, inifile:
collected 1 items 

test_fft_poisson.py F

================================================================== FAILURES ===================================================================
______________________________________________________________ test_fft_poisson _______________________________________________________________

    def test_fft_poisson():
      obj = test()
>     fft_poisson(obj)

test_fft_poisson.py:60: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <test_fft_poisson.test object at 0x7f49c8073860>

    def fft_poisson(self):
    
      if(self._comm.size != 1):
        raise Exception('FFT solver can only be used when run in serial')
    
      else:
        N_g  = self.N_ghost
>       rho  = self.physical_system.params.charge_electron * \
               self.compute_moments('density')[N_g:-N_g, N_g:-N_g]
E       AttributeError: 'test' object has no attribute 'physical_system'

../EM_fields_solver/electrostatic.py:114: AttributeError
========================================================== 1 failed in 1.54 seconds ===========================================================
```
5. `test_interp_p_3d.py` : Could not check. Computer hangs.

**Comment by mchandra** [comment]
This PR achieved its objective. Merging to master now.

**Pull request merged**
