### PR TITLE
[WIP] Performance Refactor

### PR DESCRIPTION
**Pull request by ShyamSS-95**

### CODE REVIEW

**Comment by ShyamSS-95** [comment]
Preliminary performance benchmarks with the reordering of data to allow for more efficient operation of the communicate routine(to compare against #27):
```

-------------------------------------------------------------------
|                      ,/                                         |
|                    ,'/          ____        ____                |
|                  ,' /          / __ )____  / / /_               |
|                ,'  /_____,    / __  / __ \/ / __/               |
|              .'____    ,'    / /_/ / /_/ / / /_                 |
|                   /  ,'     /_____/\____/_/\__/                 |
|                  / ,'                                           |
|                 /,'                                             |
|                /'                                               |
|-----------------------------------------------------------------|
| Copyright (C) 2017, Research Division, Quazar Techologies, Delhi|
|                                                                 |
| Bolt is free software; you can redistribute it and/or modify    |
| it under the terms of the GNU General Public License as         |
| as published by the Free Software Foundation(version 3.0)       |
-------------------------------------------------------------------
Fields Initialization Method       : ELECTROSTATIC
Fields Solver Method               : FDTD
Resolution(Nq1, Nq2, Np1, Np2, Np3): ( 64 , 128 , 16 , 16 , 16 )
Charge Electron                    : 0
Number of Devices/Node             : 4

Backend Details for Nonlinear Solver:
    Rank 0 of 0
    On Node: n0022.savio2
    Device Details:
        ArrayFire v3.6.0 (OpenCL 64bit)
        [0] NVIDIA CUDA: Tesla_K80 (Compute 1.2)
        -1- Intel(R) OpenCL: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
        -2- AMD Accelerated Parallel Processing: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
    Device Bandwidth = 155.31659725530955 GB / sec

+---------------+--------------------+------------------+
|     Method    | Time-Taken(s/iter) |  Percentage(%)   |
+---------------+--------------------+------------------+
|    TIMESTEP   |   0.800958862399   |       100        |
|  Q_ADVECTION  |   0.179965869035   |  22.4688030164   |
|   SOURCE_TS   |   0.351251177268   |  43.8538349169   |
|   FVM_SOLVER  |        0.0         |       0.0        |
|   FIELD-STEP  |        0.0         |       0.0        |
|  APPLY_BCS_F  |  4.6449132485e-05  | 0.00579919077814 |
| COMMUNICATE_F |   0.269625817195   |  33.6628795626   |
+---------------+--------------------+------------------+
Spatial Zone Cycles/s = 10227.7412544
```
When using FVM:
```
-------------------------------------------------------------------
|                      ,/                                         |
|                    ,'/          ____        ____                |
|                  ,' /          / __ )____  / / /_               |
|                ,'  /_____,    / __  / __ \/ / __/               |
|              .'____    ,'    / /_/ / /_/ / / /_                 |
|                   /  ,'     /_____/\____/_/\__/                 |
|                  / ,'                                           |
|                 /,'                                             |
|                /'                                               |
|-----------------------------------------------------------------|
| Copyright (C) 2017, Research Division, Quazar Techologies, Delhi|
|                                                                 |
| Bolt is free software; you can redistribute it and/or modify    |
| it under the terms of the GNU General Public License as         |
| as published by the Free Software Foundation(version 3.0)       |
-------------------------------------------------------------------
Fields Initialization Method       : ELECTROSTATIC
Fields Solver Method               : FDTD
Resolution(Nq1, Nq2, Np1, Np2, Np3): ( 64 , 128 , 16 , 16 , 16 )
Charge Electron                    : 0
Number of Devices/Node             : 4

Backend Details for Nonlinear Solver:
    Rank 0 of 0
    On Node: n0022.savio2
    Device Details:
        ArrayFire v3.6.0 (OpenCL 64bit)
        [0] NVIDIA CUDA: Tesla_K80 (Compute 1.2)
        -1- Intel(R) OpenCL: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
        -2- AMD Accelerated Parallel Processing: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
    Device Bandwidth = 151.62027453065227 GB / sec

+---------------+--------------------+------------------+
|     Method    | Time-Taken(s/iter) |  Percentage(%)   |
+---------------+--------------------+------------------+
|    TIMESTEP   |   0.99977541442    |       100        |
|  Q_ADVECTION  |        0.0         |       0.0        |
|   SOURCE_TS   |        0.0         |       0.0        |
|   FVM_SOLVER  |   0.864076659231   |  86.4270761982   |
|   FIELD-STEP  |        0.0         |       0.0        |
|  APPLY_BCS_F  | 1.97462516256e-05  | 0.00197506873452 |
| COMMUNICATE_F |   0.13565142556    |  13.5681897758   |
+---------------+--------------------+------------------+
FVM_SOLVER consists of:
+------------------+--------------------+---------------+
|      Method      | Time-Taken(s/iter) | Percentage(%) |
+------------------+--------------------+---------------+
|    FVM_SOLVER    |   0.864076659231   |      100      |
|  RECONSTRUCTION  |   0.324491437119   | 37.5535473216 |
|  RIEMANN-SOLVER  |   0.317113928276   | 36.6997447377 |
| DFDT_INTEGRATION |   0.222471293837   | 25.7467079408 |
+------------------+--------------------+---------------+
Spatial Zone Cycles/s = 8193.84021836
```
**NOTE**: These are preliminary benchmarks. Correctness of implementation of all functions is yet to be completed(unit tests and convergence tests)

**Comment by ShyamSS-95** [comment]
The interpolation routine in p-space seems really expensive ATM.

```
-------------------------------------------------------------------
|                      ,/                                         |
|                    ,'/          ____        ____                |
|                  ,' /          / __ )____  / / /_               |
|                ,'  /_____,    / __  / __ \/ / __/               |
|              .'____    ,'    / /_/ / /_/ / / /_                 |
|                   /  ,'     /_____/\____/_/\__/                 |
|                  / ,'                                           |
|                 /,'                                             |
|                /'                                               |
|-----------------------------------------------------------------|
| Copyright (C) 2017, Research Division, Quazar Techologies, Delhi|
|                                                                 |
| Bolt is free software; you can redistribute it and/or modify    |
| it under the terms of the GNU General Public License as         |
| as published by the Free Software Foundation(version 3.0)       |
-------------------------------------------------------------------
Fields Initialization Method       : FFT
Fields Solver Method               : FDTD
Resolution(Nq1, Nq2, Np1, Np2, Np3): ( 64 , 128 , 16 , 16 , 16 )
Charge Electron                    : -10
Number of Devices/Node             : 4

Backend Details for Nonlinear Solver:
    Rank 0 of 0
    On Node: n0018.savio2
    Device Details:
        ArrayFire v3.6.0 (OpenCL 64bit)
        [0] NVIDIA CUDA: Tesla_K80 (Compute 1.2)
        -1- Intel(R) OpenCL: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
        -2- AMD Accelerated Parallel Processing: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
    Device Bandwidth = 158.47033184924572 GB / sec

+---------------+--------------------+-------------------+
|     Method    | Time-Taken(s/iter) |   Percentage(%)   |
+---------------+--------------------+-------------------+
|    TIMESTEP   |    17.544960487    |        100        |
|  Q_ADVECTION  |   0.392630990189   |   2.23785622361   |
|   SOURCE_TS   |   0.681661617638   |   3.88522743122   |
|   FVM_SOLVER  |        0.0         |        0.0        |
|   FIELD-STEP  |   15.9256615119    |   90.7705749679   |
|  APPLY_BCS_F  | 8.86964325858e-05  | 0.000505537944366 |
| COMMUNICATE_F |   0.544788299221   |   3.10509846759   |
+---------------+--------------------+-------------------+
FIELDS-STEP consists of:
+--------------------+--------------------+-------------------+
|       Method       | Time-Taken(s/iter) |   Percentage(%)   |
+--------------------+--------------------+-------------------+
|     FIELD-STEP     |   15.9256615119    |        100        |
|    FIELD-SOLVER    |  0.00483378325358  |   0.030352166219  |
|    P_ADVECTION     |   15.8706652764    |   99.6546690667   |
|  APPLY_BCS_FIELDS  |  2.3605799911e-07  | 1.48224925497e-06 |
| COMMUNICATE_FIELDS |  0.0466960373491   |   0.29321254451   |
+--------------------+--------------------+-------------------+
Spatial Zone Cycles/s = 466.914702149
```

**Comment by ShyamSS-95** [comment]
When run in 2D2V.

Fields-free:
```
-------------------------------------------------------------------
|                      ,/                                         |
|                    ,'/          ____        ____                |
|                  ,' /          / __ )____  / / /_               |
|                ,'  /_____,    / __  / __ \/ / __/               |
|              .'____    ,'    / /_/ / /_/ / / /_                 |
|                   /  ,'     /_____/\____/_/\__/                 |
|                  / ,'                                           |
|                 /,'                                             |
|                /'                                               |
|-----------------------------------------------------------------|
| Copyright (C) 2017, Research Division, Quazar Techologies, Delhi|
|                                                                 |
| Bolt is free software; you can redistribute it and/or modify    |
| it under the terms of the GNU General Public License as         |
| as published by the Free Software Foundation(version 3.0)       |
-------------------------------------------------------------------
Fields Initialization Method       : FFT
Fields Solver Method               : FDTD
Resolution(Nq1, Nq2, Np1, Np2, Np3): ( 64 , 128 , 16 , 16 , 1 )
Charge Electron                    : 0
Number of Devices/Node             : 4

Backend Details for Nonlinear Solver:
    Rank 0 of 0
    On Node: n0018.savio2
    Device Details:
        ArrayFire v3.6.0 (OpenCL 64bit)
        [0] NVIDIA CUDA: Tesla_K80 (Compute 1.2)
        -1- Intel(R) OpenCL: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
        -2- AMD Accelerated Parallel Processing: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
    Device Bandwidth = 157.30771519540897 GB / sec

+---------------+--------------------+-----------------+
|     Method    | Time-Taken(s/iter) |  Percentage(%)  |
+---------------+--------------------+-----------------+
|    TIMESTEP   |  0.0568057924214   |       100       |
|  Q_ADVECTION  |   0.01269816172    |  22.3536389139  |
|   SOURCE_TS   |  0.0254148846806   |  44.7399527359  |
|   FVM_SOLVER  |        0.0         |       0.0       |
|   FIELD-STEP  |        0.0         |       0.0       |
|  APPLY_BCS_F  | 4.34346718363e-05  | 0.0764616951633 |
| COMMUNICATE_F |  0.0185859887907   |  32.7184746457  |
+---------------+--------------------+-----------------+
Spatial Zone Cycles/s = 144210.645619
```
With fields:
```
-------------------------------------------------------------------
|                      ,/                                         |
|                    ,'/          ____        ____                |
|                  ,' /          / __ )____  / / /_               |
|                ,'  /_____,    / __  / __ \/ / __/               |
|              .'____    ,'    / /_/ / /_/ / / /_                 |
|                   /  ,'     /_____/\____/_/\__/                 |
|                  / ,'                                           |
|                 /,'                                             |
|                /'                                               |
|-----------------------------------------------------------------|
| Copyright (C) 2017, Research Division, Quazar Techologies, Delhi|
|                                                                 |
| Bolt is free software; you can redistribute it and/or modify    |
| it under the terms of the GNU General Public License as         |
| as published by the Free Software Foundation(version 3.0)       |
-------------------------------------------------------------------
Fields Initialization Method       : FFT
Fields Solver Method               : FDTD
Resolution(Nq1, Nq2, Np1, Np2, Np3): ( 64 , 128 , 16 , 16 , 1 )
Charge Electron                    : -10
Number of Devices/Node             : 4

Backend Details for Nonlinear Solver:
    Rank 0 of 0
    On Node: n0018.savio2
    Device Details:
        ArrayFire v3.6.0 (OpenCL 64bit)
        [0] NVIDIA CUDA: Tesla_K80 (Compute 1.2)
        -1- Intel(R) OpenCL: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
        -2- AMD Accelerated Parallel Processing: Intel(R)_Xeon(R)_CPU_E5-2623_v3 @ 3.00GHz (Compute 1.2)
    Device Bandwidth = 153.11717250973248 GB / sec

+---------------+--------------------+-----------------+
|     Method    | Time-Taken(s/iter) |  Percentage(%)  |
+---------------+--------------------+-----------------+
|    TIMESTEP   |   0.115834403746   |       100       |
|  Q_ADVECTION  |  0.0252034616942   |  21.7581831297  |
|   SOURCE_TS   |  0.0406027831654   |  35.0524385262  |
|   FVM_SOLVER  |        0.0         |       0.0       |
|   FIELD-STEP  |  0.0129589727609   |  11.1874990002  |
|  APPLY_BCS_F  | 8.53727359583e-05  | 0.0737024003208 |
| COMMUNICATE_F |  0.0368682488356   |  31.8284099053  |
+---------------+--------------------+-----------------+
FIELDS-STEP consists of:
+--------------------+--------------------+------------------+
|       Method       | Time-Taken(s/iter) |  Percentage(%)   |
+--------------------+--------------------+------------------+
|     FIELD-STEP     |  0.0129589727609   |       100        |
|    FIELD-SOLVER    |  0.00393446129147  |  30.3609040937   |
|    P_ADVECTION     |  0.00318663663203  |  24.5901946922   |
|  APPLY_BCS_FIELDS  | 2.90351338906e-07  | 0.00224054285985 |
| COMMUNICATE_FIELDS |  0.00208288136095  |  16.0728894132   |
+--------------------+--------------------+------------------+
Spatial Zone Cycles/s = 70721.6486213
```

**Comment by ShyamSS-95** [comment]
**Commit**: 236288f

With the exception of the minmod limiter used in the FVM solver, all other solver components seem to be working alright.

**Comment by mchandra** [comment]
Whats wrong with the minmod limiter?

**Pull request merged**
